### ISSUE TITLE
A way to debug or test components

### ISSUE THREAD

**Issue by dmitryrn** [maxence-charriere/go-app#473]
Is there a way to debug or write unit tests for components?

**Comment by dmitryrn** [comment]
I found the TestMatch method.

I'm trying to do something like this:
```go
func Test_GameList(t *testing.T) {
	comp := MyComponentCreate()
	ui := comp.Render()
	
	err := app.TestMatch(ui, app.TestUIDescriptor{
		Path:     app.TestPath(),
		Expected: app.Div(),
	})
	assert.Nil(t, err)
}
```

and app.TestMatch trying to mount the component, but it fails. Seems like it tries to mount it using the browser's window object.

```log
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x121762b]

goroutine 6 [running]:
testing.tRunner.func1.1(0x124e160, 0x14362b0)
	/Users/user/.gvm/gos/go1.15/src/testing/testing.go:1057 +0x30d
testing.tRunner.func1(0xc000001b00)
	/Users/user/.gvm/gos/go1.15/src/testing/testing.go:1060 +0x41a
panic(0x124e160, 0x14362b0)
	/Users/user/.gvm/gos/go1.15/src/runtime/panic.go:969 +0x175
github.com/maxence-charriere/go-app/v7/pkg/app.(*browserWindow).Get(0x0, 0x128f9a6, 0x8, 0xc000012b00, 0xc0000610d0)
	<autogenerated>:1 +0x2b
github.com/maxence-charriere/go-app/v7/pkg/app.(*elem).mount(0xc00012c120, 0x0, 0x0)
	/Users/user/.gvm/pkgsets/go1.15/global/pkg/mod/github.com/maxence-charriere/go-app/v7@v7.0.6/pkg/app/element.go:84 +0xca
github.com/maxence-charriere/go-app/v7/pkg/app.mount(0x17ca2d8, 0xc00012c120, 0x127fdc0, 0xc00000e560)
	/Users/user/.gvm/pkgsets/go1.15/global/pkg/mod/github.com/maxence-charriere/go-app/v7@v7.0.6/pkg/app/node.go:186 +0x52
github.com/maxence-charriere/go-app/v7/pkg/app.TestMatch(0x17ca2d8, 0xc00012c120, 0x0, 0x0, 0x0, 0x17ca2d8, 0xc00012c360, 0x1441b40, 0xc00004a718)
	/Users/user/.gvm/pkgsets/go1.15/global/pkg/mod/github.com/maxence-charriere/go-app/v7@v7.0.6/pkg/app/testing.go:75 +0x18d5
github.com/user/repo/components.Test_GameList(0xc000001b00)
	/Users/user/projects/project/web/components/gamelist_test.go:19 +0x2c5
testing.tRunner(0xc000001b00, 0x12a3df0)
	/Users/user/.gvm/gos/go1.15/src/testing/testing.go:1108 +0xef
created by testing.(*T).Run
	/Users/user/.gvm/gos/go1.15/src/testing/testing.go:1159 +0x386
```

**Comment by maxence-charriere** [comment]
This is probably because the test is launched in a non wasm environment.

Try to launch the test with:
```
GOARCH=wasm GOOS=js go test
```

Tips: you can skip the test in nonwasm environment by calling a func like the following:
```go
func testSkipNonWasm(t *testing.T) {
	if goarch := runtime.GOARCH; goarch != "wasm" {
		t.Skip()
	}
}
```
