### ISSUE TITLE
Failed to execute 'replaceChild' on 'Node'

### ISSUE THREAD

**Issue by jwmach1** [maxence-charriere/go-app#484]
version `v7.0.5`.

this does not happen every time.  My suspicion is that there is a relationship between the go-routine I have in OnMount that goes checks session status, then calls Update(). Something about the timing between Render() and the Update().

What if this error message included some details about _what_ node couldn't be replaced?  Maybe it's DOM path?

Here is the stack trace:
```
panic: JavaScript error: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node. [recovered]
wasm_exec.js:47 	panic: JavaScript error: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.
wasm_exec.js:47 
wasm_exec.js:47 goroutine 1 [running]:
wasm_exec.js:47 github.com/maxence-charriere/go-app/v7/pkg/app.run.func1()
wasm_exec.js:47 	/Users/jameswilson/go/pkg/mod/github.com/maxence-charriere/go-app/v7@v7.0.5/pkg/app/app_wasm.go:25 +0x4
wasm_exec.js:47 panic(0xb03c0, 0x971d70)
wasm_exec.js:47 	/usr/local/go/src/runtime/panic.go:969 +0x19
wasm_exec.js:47 syscall/js.Value.Call(0x7ff8000100000391, 0x950288, 0xd09d8, 0xc, 0x96b420, 0x2, 0x2, 0xee77b8, 0x20)
wasm_exec.js:47 	/usr/local/go/src/syscall/js/js.go:400 +0x34
wasm_exec.js:47 github.com/maxence-charriere/go-app/v7/pkg/app.value.Call(0x7ff8000100000391, 0x950288, 0xd09d8, 0xc, 0x96b420, 0x2, 0x2, 0x1, 0x96b420)
wasm_exec.js:47 	/Users/jameswilson/go/pkg/mod/github.com/maxence-charriere/go-app/v7@v7.0.5/pkg/app/js_wasm.go:23 +0x7
wasm_exec.js:47 github.com/maxence-charriere/go-app/v7/pkg/app.(*elem).replaceChildAt(0x949d40, 0x1, 0xed8c48, 0x96f7a0, 0x967838, 0x4)
wasm_exec.js:47 	/Users/jameswilson/go/pkg/mod/github.com/maxence-charriere/go-app/v7@v7.0.5/pkg/app/element.go:235 +0x1e
wasm_exec.js:47 github.com/maxence-charriere/go-app/v7/pkg/app.(*elem).update(0x949d40, 0x1423a0, 0x96f680, 0x0, 0x0)
wasm_exec.js:47 	/Users/jameswilson/go/pkg/mod/github.com/maxence-charriere/go-app/v7@v7.0.5/pkg/app/element.go:155 +0x35
wasm_exec.js:47 github.com/maxence-charriere/go-app/v7/pkg/app.update(0x1423a0, 0x949d40, 0x1423a0, 0x96f680, 0x0, 0x0)
wasm_exec.js:47 	/Users/jameswilson/go/pkg/mod/github.com/maxence-charriere/go-app/v7@v7.0.5/pkg/app/node.go:197 +0x8
wasm_exec.js:47 github.com/maxence-charriere/go-app/v7/pkg/app.(*elem).update(0x9541b0, 0x1423a0, 0x96fa70, 0x0, 0x0)
wasm_exec.js:47 	/Users/jameswilson/go/pkg/mod/github.com/maxence-charriere/go-app/v7@v7.0.5/pkg/app/element.go:153 +0x23
wasm_exec.js:47 github.com/maxence-charriere/go-app/v7/pkg/app.update(0x1423a0, 0x9541b0, 0x1423a0, 0x96fa70, 0x0, 0x1e)
wasm_exec.js:47 	/Users/jameswilson/go/pkg/mod/github.com/maxence-charriere/go-app/v7@v7.0.5/pkg/app/node.go:197 +0x8
wasm_exec.js:47 github.com/maxence-charriere/go-app/v7/pkg/app.(*elem).update(0x954000, 0xeda930, 0x96f8c0, 0x0, 0x0)
wasm_exec.js:47 	/Users/jameswilson/go/pkg/mod/github.com/maxence-charriere/go-app/v7@v7.0.5/pkg/app/element.go:153 +0x23
wasm_exec.js:47 github.com/maxence-charriere/go-app/v7/pkg/app.update(0xeda930, 0x954000, 0xeda930, 0x96f8c0, 0x10, 0x10)
wasm_exec.js:47 	/Users/jameswilson/go/pkg/mod/github.com/maxence-charriere/go-app/v7@v7.0.5/pkg/app/node.go:197 +0x8
wasm_exec.js:47 github.com/maxence-charriere/go-app/v7/pkg/app.(*Compo).updateRoot(0x88e0e0, 0x8b9d01, 0x143901)
wasm_exec.js:47 	/Users/jameswilson/go/pkg/mod/github.com/maxence-charriere/go-app/v7@v7.0.5/pkg/app/component.go:254 +0x5
wasm_exec.js:47 github.com/maxence-charriere/go-app/v7/pkg/app.(*Compo).Update.func1()
wasm_exec.js:47 	/Users/jameswilson/go/pkg/mod/github.com/maxence-charriere/go-app/v7@v7.0.5/pkg/app/component.go:122 +0x5
wasm_exec.js:47 github.com/maxence-charriere/go-app/v7/pkg/app.run()
wasm_exec.js:47 	/Users/jameswilson/go/pkg/mod/github.com/maxence-charriere/go-app/v7@v7.0.5/pkg/app/app_wasm.go:55 +0x3a
wasm_exec.js:47 github.com/maxence-charriere/go-app/v7/pkg/app.Run(...)
wasm_exec.js:47 	/Users/jameswilson/go/pkg/mod/github.com/maxence-charriere/go-app/v7@v7.0.5/pkg/app/app.go:73
wasm_exec.js:47 
```

**Comment by maxence-charriere** [comment]
Are you displaying a ui element that is stored in a component field ?

**Comment by maxence-charriere** [comment]
Render and update are both guaranteed to be executed on the UI goroutine.
Modifying a component field in another gouroutine should be avoided.
use app.Dispatch if you want to modify a field into another goroutine.

**Comment by jwmach1** [comment]
it does look like that's the case. Still doing research.

**Comment by jwmach1** [comment]
as you indicated, using app.Dispatch around UI element modification fixed it
