### ISSUE TITLE
Panic with bootstrap table

### ISSUE THREAD

**Issue by maxim0r** [maxence-charriere/go-app#734]
I want to make a collapsing navigation list with a [bootstrap table](https://bootstrap-table.com/) in the panel. It works, but I get an error after a certain number of navigation operations. If without table, there is no error. 
I have written a test example. 
Please help me to understand it.
```go
package main

import (
	"log"
	"math/rand"
	"net/http"
	"strconv"
	"strings"

	"github.com/maxence-charriere/go-app/v9/pkg/app"
)

// navlist component
type navlist struct {
	app.Compo
	items map[string]string

	folder string
	item   string
}

func (c *navlist) OnNav(ctx app.Context) {
	path := ctx.Page().URL().Path
	switch {
	case strings.HasPrefix(path, "/folder/"):
		c.folder = strings.TrimPrefix(path, "/folder/")
	case strings.HasPrefix(path, "/items/"):
		c.folder = strings.TrimPrefix(path, "/items/")
	}
	c.item = ctx.Page().URL().Fragment

	c.items = map[string]string{
		"0:0": "/",
		"1:0": "/folder/1", "1:1": "/items/1#1", "1:2": "/items/1#2", "1:3": "/items/1#3", "1:4": "/items/1#4",
		"2:0": "/folder/2", "2:1": "/items/2#1", "2:2": "/items/2#2", "2:3": "/items/2#3",
	}
}

func (c *navlist) Render() app.UI {
	return app.Ul().Body(
		app.Range(c.items).Map(func(k string) app.UI {
			a := strings.Split(k, ":")
			if c.folder != a[0] && a[1] != "0" {
				return app.Text("")
			}
			return app.Li().Body(app.A().Href(c.items[k]).Text(c.items[k]))
		}),
	)
}

// folder component
type folder struct {
	app.Compo
	name string
}

func (c *folder) OnNav(ctx app.Context) {
	c.name = ctx.Page().URL().Path
}

func (c *folder) Render() app.UI {
	return app.Div().Body(
		&navlist{},
		app.H1().Text("Folder:"+c.name),
		&table{Data: tableData()},
	)
}

// item component
type item struct {
	app.Compo
	folder string
	num    string
}

func (c *item) OnNav(ctx app.Context) {
	c.folder = strings.TrimPrefix(ctx.Page().URL().Path, "/items/")
	c.num = ctx.Page().URL().Fragment
}

func (c *item) Render() app.UI {
	return app.Div().Body(
		&navlist{},
		app.H1().Text("Item folder:"+c.folder),
		app.H2().Text("Item name:"+c.num),
		&table{Data: tableData()},
	)
}

// table component
type table struct {
	app.Compo
	Data [][]int
}

func (c *table) Render() app.UI {
	return app.Div().Body(
		app.Table().
			Attr("data-toggle", "table").Attr("data-search", "true").
			Body(
				app.THead().Body(
					app.Tr().Body(
						app.Th().Text("ID"), app.Th().Text("Value"),
					),
				),
				app.TBody().Body(
					app.Range(c.Data).Slice(func(i int) app.UI {
						return app.Tr().Body(
							app.Range(c.Data[i]).Slice(func(j int) app.UI {
								return app.Td().Body(app.Text(strconv.Itoa(c.Data[i][j])))
							}),
						)
					}),
				),
			),

		app.Script().Src("https://unpkg.com/bootstrap-table@1.20.1/dist/bootstrap-table.min.js"),
	)
}

// home component
type home struct {
	app.Compo
}

func (c *home) Render() app.UI {
	return app.Div().Body(
		&navlist{},
		app.H1().Text("Home"),
	)
}

func main() {
	app.Route("/", &home{})
	app.RouteWithRegexp("/folder.*", &folder{})
	app.RouteWithRegexp("/items.*", &item{})
	app.RunWhenOnBrowser()

	http.Handle("/", &app.Handler{
		Name:        "Hello",
		Description: "An Hello World! example",
		Scripts: []string{
			"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js",
			"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js",
		},
		Styles: []string{
			"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css",
			"https://unpkg.com/bootstrap-table@1.20.1/dist/bootstrap-table.min.css",
		},
	})

	if err := http.ListenAndServe(":8123", nil); err != nil {
		log.Fatal(err)
	}
}

func tableData() [][]int {
	var data [][]int
	for i := 0; i < rand.Intn(10); i++ {
		data = append(data, []int{i, rand.Intn(100)})
	}
	return data
}
```

Error:
```
panic: JavaScript error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. [recovered]
wasm_exec.js:22 	panic: JavaScript error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
wasm_exec.js:22 
wasm_exec.js:22 goroutine 1 [running]:
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.RunWhenOnBrowser.func1()
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/app.go:108 +0x4
wasm_exec.js:22 panic({0xb5da0, 0x9c4d90})
wasm_exec.js:22 	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/panic.go:844 +0x33
wasm_exec.js:22 syscall/js.Value.Call({{}, 0x7ff8000100000553, 0x9a9d18}, {0xd4a83, 0xb}, {0x8780a0, 0x1, 0x1})
wasm_exec.js:22 	/opt/homebrew/Cellar/go/1.18.3/libexec/src/syscall/js/js.go:389 +0x31
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.value.Call({{{}, 0x7ff8000100000553, 0x9a9d18}}, {0xd4a83, 0xb}, {0x8780a0, 0x1, 0x1})
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/js_wasm.go:21 +0x7
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.value.removeChild(...)
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/js_wasm.go:103
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.(*elem).removeChildAt(0x9b7180, 0x1)
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/element.go:275 +0x24
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.(*elem).update(0x9b7180, {0xf6b6a8, 0x9c3d60})
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/element.go:189 +0x51
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.update({0xf6b6a8, 0x9b7180}, {0xf6b6a8, 0x9c3d60})
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/node.go:199 +0x8
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.(*elem).update(0x9b6e60, {0xf6b778, 0x9c3a40})
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/element.go:170 +0x38
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.update({0xf6b778, 0x9b6e60}, {0xf6b778, 0x9c3a40})
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/node.go:199 +0x8
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.(*elem).update(0x9b6dc0, {0x15c0b0, 0x9c39a0})
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/element.go:170 +0x38
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.update({0x15c0b0, 0x9b6dc0}, {0x15c0b0, 0x9c39a0})
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/node.go:199 +0x8
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.(*Compo).updateRoot(0x8b3ea0)
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/component.go:386 +0x5
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.(*Compo).update(0x8b3ea0, {0x15c3f0, 0x8b3f80})
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/component.go:369 +0xc9
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.update({0x15c3f0, 0x8b3ea0}, {0x15c3f0, 0x8b3f80})
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/node.go:199 +0x8
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.(*elem).update(0x9b6b40, {0x15c0b0, 0x9c37c0})
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/element.go:170 +0x38
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.update({0x15c0b0, 0x9b6b40}, {0x15c0b0, 0x9c37c0})
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/node.go:199 +0x8
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.(*Compo).updateRoot(0x980b80)
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/component.go:386 +0x5
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.(*engine).updateComponents(0x87e480)
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/engine.go:419 +0x18
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.(*engine).start.func1()
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/engine.go:347 +0x1c
wasm_exec.js:22 sync.(*Once).doSlow(0x87e4ec, 0x879a50)
wasm_exec.js:22 	/opt/homebrew/Cellar/go/1.18.3/libexec/src/sync/once.go:68 +0x9
wasm_exec.js:22 sync.(*Once).Do(0x87e4ec, 0x879a50)
wasm_exec.js:22 	/opt/homebrew/Cellar/go/1.18.3/libexec/src/sync/once.go:59 +0x6
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.(*engine).start(0x87e480, {0x15a9d0, 0x81e040})
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/engine.go:323 +0x4
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.RunWhenOnBrowser()
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/app.go:156 +0x9d
wasm_exec.js:22 main.main()
wasm_exec.js:22 	/Users/moreshnikov/work/projects/examples/wasm/go-app-issue2/main.go:137 +0x11
wasm_exec.js:101 exit code: 2
exit @ wasm_exec.js:101
runtime.wasmExit @ wasm_exec.js:225
$runtime.wasmExit @ app.wasm:0xe9f7c
$runtime.exit @ app.wasm:0xe9daa
$runtime.fatalpanic.func2 @ app.wasm:0x83b54
$runtime.systemstack @ app.wasm:0xe7317
$runtime.fatalpanic @ app.wasm:0x83cb6
$runtime.gopanic @ app.wasm:0x8265b
$github.com_maxence_charriere_go_app_v9_pkg_app.RunWhenOnBrowser.func1 @ app.wasm:0x72a312
$runtime.gopanic @ app.wasm:0x82318
$wasm_pc_f_loop @ app.wasm:0xe9d63
$wasm_export_resume @ app.wasm:0xe9d44
_resume @ wasm_exec.js:538
(anonymous) @ wasm_exec.js:264
setTimeout (async)
runtime.scheduleTimeoutEvent @ wasm_exec.js:262
$runtime.scheduleTimeoutEvent @ app.wasm:0xe9ff4
$runtime.beforeIdle @ app.wasm:0x20125
$runtime.findrunnable @ app.wasm:0x95c20
$runtime.schedule @ app.wasm:0x99552
$runtime.park_m @ app.wasm:0x9a5a3
$runtime.mcall @ app.wasm:0xe7218
$runtime.gopark @ app.wasm:0x890ce
$runtime.selectgo @ app.wasm:0xadb09
$github.com_maxence_charriere_go_app_v9_pkg_app.__engine_.start.func1 @ app.wasm:0x752bf4
$wasm_pc_f_loop @ app.wasm:0xe9d63
$wasm_export_resume @ app.wasm:0xe9d44
_resume @ wasm_exec.js:538
(anonymous) @ wasm_exec.js:549
```

**Comment by maxence-charriere** [comment]
That is weird, I copy/pasted your example and I m unable to trigger that error.

**Comment by maxence-charriere** [comment]
Look like boostrap table uses javascript and do operations directly on the dom. My guess is that while doing it, the dom is modified and the dom state is out of sync with go-app, leading to the error you mentioned.

**Comment by maxim0r** [comment]
Thanks for the answer, I will make my own table component
