### ISSUE TITLE
panic when taking a numeric value

### ISSUE THREAD

**Issue by maxim0r** [maxence-charriere/go-app#746]
Hi! 
I want to get a numeric value on a button click, but I get a panic. 
The JS type seems to match (4 == Numeric). 
Is it my mistake or the go-app?

Example code:
```go
package main

import (
	"net/http"

	"github.com/maxence-charriere/go-app/v9/pkg/app"
)

type hello struct {
	app.Compo
}

func (h *hello) Render() app.UI {
	return app.Div().Body(
		app.Button().
			Type("button").
			ID("button1").
			Value(1).
			Text("test").
			OnClick(func(ctx app.Context, e app.Event) {
				app.Log("Value type:", ctx.JSSrc().Get("value").Type())
				v := ctx.JSSrc().Get("value").Int()
				app.Log("Value:", v)
			}),
	)
}

func main() {
	app.Route("/", &hello{})
	app.RunWhenOnBrowser()

	http.Handle("/", &app.Handler{
		Name:        "Hello",
		Description: "An Hello World! example",
	})

	if err := http.ListenAndServe(":8778", nil); err != nil {
		panic(err)
	}
}
```

Log:
```
Value type: 4
wasm_exec.js:22 panic: syscall/js: call of Value.Int on string [recovered]
wasm_exec.js:22 	panic: syscall/js: call of Value.Int on string
wasm_exec.js:22 
wasm_exec.js:22 goroutine 1 [running]:
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.RunWhenOnBrowser.func1()
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/app.go:108 +0x4
wasm_exec.js:22 panic({0x5ff20, 0x80a270})
wasm_exec.js:22 	/opt/homebrew/Cellar/go/1.18.4/libexec/src/runtime/panic.go:844 +0x33
wasm_exec.js:22 syscall/js.Value.float({{}, 0x7ff800020000002d, 0x81e440}, {0xc6327, 0x9})
wasm_exec.js:22 	/opt/homebrew/Cellar/go/1.18.4/libexec/src/syscall/js/js.go:442 +0x10
wasm_exec.js:22 syscall/js.Value.Int(...)
wasm_exec.js:22 	/opt/homebrew/Cellar/go/1.18.4/libexec/src/syscall/js/js.go:459
wasm_exec.js:22 main.(*hello).Render.func1({0x14dcf0, 0x83c600}, {{0x14daa8, 0x81d310}})
wasm_exec.js:22 	/Users/moreshnikov/work/projects/examples/wasm/go-app-number/main.go:22 +0x18
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.makeJsEventHandler.func1.1.1()
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/node.go:159 +0x6
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.(*engine).Emit(0x87e480, {0xee7368, 0x85ec80}, 0x84a4c0)
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/engine.go:75 +0x7
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.uiContext.Emit(...)
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/context.go:263
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.makeJsEventHandler.func1.1({0x14dcf0, 0x83c600})
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/node.go:154 +0xe
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.(*engine).handleDispatch(0x87e480, {0x0, {0xee7368, 0x85ec80}, 0x836fc0})
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/engine.go:370 +0x23
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.(*engine).start.func1()
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/engine.go:344 +0x1a
wasm_exec.js:22 sync.(*Once).doSlow(0x87e4ec, 0x879a68)
wasm_exec.js:22 	/opt/homebrew/Cellar/go/1.18.4/libexec/src/sync/once.go:68 +0x9
wasm_exec.js:22 sync.(*Once).Do(0x87e4ec, 0x879a68)
wasm_exec.js:22 	/opt/homebrew/Cellar/go/1.18.4/libexec/src/sync/once.go:59 +0x6
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.(*engine).start(0x87e480, {0x14b650, 0x81e040})
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/engine.go:323 +0x4
wasm_exec.js:22 github.com/maxence-charriere/go-app/v9/pkg/app.RunWhenOnBrowser()
wasm_exec.js:22 	/Users/moreshnikov/go/pkg/mod/github.com/maxence-charriere/go-app/v9@v9.5.1/pkg/app/app.go:156 +0x9d
wasm_exec.js:22 main.main()
wasm_exec.js:22
```

Thanks for the great product!

**Comment by maxim0r** [comment]
Exactly! I apologize for my inattention :(
