### ISSUE TITLE
Unable to run app with a prefix

### ISSUE THREAD

**Issue by kidandcat** [maxence-charriere/go-app#971]
I need to run the app with a prefix, as it cannot interfere with other GoApps in the same application (mine is a package).

Example:
```
	app.Route("/demo/hello", func() app.Composer {
		return &hello{}
	})

	app.RunWhenOnBrowser()

	http.Handle("/demo", http.StripPrefix("/demo", &app.Handler{
		Name:        "Hello",
		Description: "An Hello World! example",
	}))

	if err := http.ListenAndServe(":8000", nil); err != nil {
		log.Fatal(err)
	}
```

I have tried with and without `StripPrefix`, but the GoApp router always returns a `404 page not found` error.
I have also tried with `Resources: app.PrefixedLocation("/demo")`, same 404 error.

PD: To give some context, I want to replicate what `pprof` package does, which registers an http endpoint when imported, but I want to serve a complete frontend too, using GoApp.
For this case, I need EVERYTHING to be served with a prefix, as I cannot interfere in any way with the rest of the registered endpoints.

**Comment by oderwat** [comment]
I leave this here: https://github.com/maxence-charriere/go-app/blob/ab2c53a7f8b25cbd0686c841148a9e4fedb049bb/pkg/app/resource.go#L65C1-L80C1

P.S.: I had problems using it, but probably did something wrong. It was a long time ago.

**Comment by kidandcat** [comment]
So, it looks I did not properly understood the new routing, because I though `/demo` would match `/demo/hello`, but it looks I have to use `/demo/*`.

I advanced some steps with this code:

```go
	app.Route("/hello", func() app.Composer {
		println("Route /hello")
		return &hello{}
	})

	app.RunWhenOnBrowser()

	http.Handle("/demo/*", http.StripPrefix("/demo", &app.Handler{
		Name:        "Hello",
		Description: "An Hello World! example",
		Resources:   app.PrefixedLocation("/demo"),
	}))

	if err := http.ListenAndServe(":8000", nil); err != nil {
		log.Fatal(err)
	}
```


But now the http package is panicking:

```
http: panic serving [::1]:58290: runtime error: invalid memory address or nil pointer dereference
goroutine 202 [running]:
net/http.(*conn).serve.func1()
        /opt/homebrew/Cellar/go/1.22.4/libexec/src/net/http/server.go:1898 +0xb0
panic({0x102e74a40?, 0x10317b560?})
        /opt/homebrew/Cellar/go/1.22.4/libexec/src/runtime/panic.go:770 +0x124
github.com/maxence-charriere/go-app/v10/pkg/app.(*prefixedResourceResolver).ServeHTTP(0x102d6e1ca?, {0x102ee5ca8?, 0x14000204460?}, 0x1400013e240?)
        <autogenerated>:1 +0x30
github.com/maxence-charriere/go-app/v10/pkg/app.(*Handler).ServeHTTP(0x1400016c2c8, {0x102ee5ca8, 0x14000204460}, 0x14000200900)
        /Users/jairo/go/pkg/mod/github.com/maxence-charriere/go-app/v10@v10.0.5/pkg/app/http.go:491 +0x468
main.main.StripPrefix.func2({0x102ee5ca8, 0x14000204460}, 0x14000360b40)
        /opt/homebrew/Cellar/go/1.22.4/libexec/src/net/http/server.go:2211 +0x278
net/http.HandlerFunc.ServeHTTP(0x10318d080?, {0x102ee5ca8?, 0x14000204460?}, 0x102c8bcb8?)
        /opt/homebrew/Cellar/go/1.22.4/libexec/src/net/http/server.go:2166 +0x38
net/http.(*ServeMux).ServeHTTP(0x10318d080, {0x102ee5ca8, 0x14000204460}, 0x14000360b40)
        /opt/homebrew/Cellar/go/1.22.4/libexec/src/net/http/server.go:2691 +0x204
net/http.serverHandler.ServeHTTP({0x14000488210?}, {0x102ee5ca8?, 0x14000204460?}, 0x6?)
        /opt/homebrew/Cellar/go/1.22.4/libexec/src/net/http/server.go:3146 +0xbc
net/http.(*conn).serve(0x1400034ccf0, {0x102ee6700, 0x14000120de0})
        /opt/homebrew/Cellar/go/1.22.4/libexec/src/net/http/server.go:2039 +0x508
created by net/http.(*Server).Serve in goroutine 1
        /opt/homebrew/Cellar/go/1.22.4/libexec/src/net/http/server.go:3294 +0x3f0
        ```

**Comment by kidandcat** [comment]
Got it working, for future reference:

```go
	app.Route("/hello", func() app.Composer { return &Hello{} })
	
	http.Handle("/_golive/*", http.StripPrefix("/_golive", gzhttp.GzipHandler(&app.Handler{
		Name:        "Hello",
		Description: "An Hello World! example",
		Resources:   ResourceFS("_golive"),
	})))
```

And my resolver with embed resources:
```go
//go:embed web
var web embed.FS

var _ app.ResourceResolver = (*embeddedResourceResolver)(nil)

func ResourceFS(prefix string) app.ResourceResolver {
	return embeddedResourceResolver{
		prefix:  prefix,
		Handler: http.FileServer(http.FS(web)),
	}
}

type embeddedResourceResolver struct {
	prefix string
	http.Handler
}

func (r embeddedResourceResolver) Resolve(location string) string {
	result := location
	if location == "" {
		result = "/" + r.prefix
	}
	if location[0] == '/' {
		result = "/" + r.prefix + location
	}
	return result
}
```

**Comment by oderwat** [comment]
@maxence-charriere I think something like that could go into an examples directory in the new documentation, especially with the embedded data. I made an example for our builder tooling too, that can embed all data into the executable. This is especially useful for writing a tool. Our example also uses `webview` and does just open it as application.
